[book]
authors = ["devs@Renuo"]
language = "en"
src = ""
title = "Renuo - Application Setup Guide"

[build]
create-missing = false
use-default-preprocessors = false

[output.html.search]
limit-results = 10
