sudo: false
language: ruby
rvm:
  - 2.3.0
addons:
  apt:
    packages:
    - zsh
  postgresql: '9.4'
services:
  - postgresql
bundler_args: --without production development --deployment --jobs=3 --retry=3
cache:
  bundler: true
  apt: true
  directories:
    - coverage
    - node_modules
before_install:
  - export TZ=Europe/Zurich
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/setup
notifications:
  email:
    on_success: change
    on_failure: always
